### ISSUE TITLE
Testing neuripp

### ISSUE THREAD

**Issue by Mattstorey** [emzodls/neuripp#1]
Hi, 

I would like to test out your models but I'm having trouble running them.

I have tried a simple sample command with an input of short peptide sequences:

    classify.py -w /home/matt/softwear/neuripp/weights/ -i sequences.faa

However, I get the output below. 
Sorry for the naive question, any ideas where I'm going wrong??

    This file is part of NeuRiPP.

    NeuRiPP is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    NeuRiPP is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

     You should have received a copy of the GNU Affero General Public License
     along with NeuRiPP.  If not, see <http://www.gnu.org/licenses/>.
      : No such file or directory
      import: not authorized `tensorflow' @ error/constitute.c/WriteImage/1028.
      from: can't read /var/mail/tensorflow
      from: can't read /var/mail/utils
      from: can't read /var/mail/models
      import: not authorized `argparse' @ error/constitute.c/WriteImage/1028.
     from: can't read /var/mail/glob
     import: not authorized `os' @ error/constitute.c/WriteImage/1028. 
    /home/matt/softwear/neuripp/classify.py: line 33: syntax error near unexpected token `('
    /home/matt/softwear/neuripp/classify.py: line 33: `def check_positive(value):

**Comment by emzodls** [comment]
Hi Matt, a couple of things...it looks like it's trying to run the program line per line (even the comments). What version of python are you using? I'd try the command python/python3 classify.py instead of just using classify.py to see if that solves it.

**Comment by Mattstorey** [comment]
That did the trick, cheers! Works great now.
